Create database Project;

Use Project;

CREATE TABLE IF NOT EXISTS User(
userName VARCHAR(255) NOT NULL,
Password VARCHAR(255) NOT NULL,
Id INT NOT NULL,
Admin BIT NOT NULL,
Driver BIT NOT NULL,
Name VARCHAR(255) NOT NULL,
Age INT NOT NULL,
Address VARCHAR(255) NOT NULL,
PhoneNumber INT NOT NULL,
emailAddress VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Passwords(
Id INT NOT NULL,
Password VARCHAR(255) NOT NULL,
emailAddress VARCHAR(255) NOT NULL,
questionID1 INT NOT NULL,
Answer1 VARCHAR(255) NOT NULL,
questionID1 INT NOT NULL,
Answer1 VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS securityQuestions(
questionId INT NOT NULL,
Question VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Admin(
Id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Driver(
Id INT NOT NULL,
driversLicense VARCHAR(255) NOT NULL
);


